### ISSUE TITLE
bug for version 2.0

### ISSUE THREAD

**Issue by giatuyentiensinh** [salmanzafar949/MQTT_Laravel#25]
Hi @salmanzafar949,

I found the bug in **Mqtt.php** at line 101.

The **MqttService.php** have 8 parameters but in the **Mqtt.php** you passed 7 paramters. You missing **timeout**

Here is the log

```
local.ERROR: Too few arguments to function Salman\Mqtt\MqttClass\MqttService::__construct(), 7 passed in /opt/lampp/htdocs/osluad/vendor/salmanzafar/laravel-mqtt/src/MqttClass/Mqtt.php on line 101 and exactly 8 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Salman\\Mqtt\\MqttClass\\MqttService::__construct(), 7 passed in /opt/lampp/htdocs/osluad/vendor/salmanzafar/laravel-mqtt/src/MqttClass/Mqtt.php on line 101 and exactly 8 expected at /opt/lampp/htdocs/osluad/vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php:36)
[stacktrace]
#0 /opt/lampp/htdocs/osluad/vendor/salmanzafar/laravel-mqtt/src/MqttClass/Mqtt.php(101): Salman\\Mqtt\\MqttClass\\MqttService->__construct('****', '****', 216, '***', '***', '***', false)
#1 /opt/lampp/htdocs/osluad/app/Http/Controllers/API/ProjectController.php(113): Salman\\Mqtt\\MqttClass\\Mqtt->ConnectAndSubscribe('#', Object(Closure))
```

**Comment by salmanzafar949** [comment]
fixed in v2.0.2
